### ISSUE TITLE
changing dropdowns to "bottom third", "middle third", "top third" or something" 

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/police_misconduct_pudding#11]

**Comment by sdl60660** [comment]
<img width="364" alt="Screen Shot 2020-10-26 at 1 38 16 PM" src="https://user-images.githubusercontent.com/12772904/97207526-82ac6e00-1790-11eb-8f8b-73ce09894be0.png">

Getting more issues here with the line spacing/select box sizing. Might need to talk this one through, I can't figure out how to incorporate the changes without it getting pretty wordy/big/confusing.

**Comment by sdl60660** [comment]
Need to fix some of the spacing, but the change here has been made and a note was added to the bottom regarding "higher", "middle", "lower" income districts.
