### ISSUE TITLE
highlighting in complaint pop-out on square chart

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/police_misconduct_pudding#19]
Just also wanted to point out the highlighting in this: I recognize that these are unedited complaints, but it's OUR choice on what to highlight within it. I'd strongly urge against highlighting up to the word "f*ggot."

**Comment by sdl60660** [comment]
Totally makes sense. We could also choose to highlight a different complaint here altogether (I could look for another serious, but unsustained physical abuse complaint)?

**Comment by jadiehm** [comment]
Highlighting another complaint might be the safest call if you can find one pretty easily.

**Comment by sdl60660** [comment]
Yeah, (unfortunately) there are many jarring stories to choose from here.

As I'm looking for a new complaint, I feel like I'm trying to strike a balance a little in showing a complaint with a story that is somewhat jarring and speaks to the egregiousness of some of the officer behavior here, but without crossing lines that might be unnecessarily upsetting for the reader, if that makes sense? I worry a little that for someone who has been a victim of police violence or other racially-motivated violence, many of these descriptions could cross a line, and I'm not sure exactly how to balance that with the value of really contextualizing how awful some of the situations some of these complaints describe are. I'm going to put a few candidate complaints for highlighting on this issue thread, but let me know if any of that feels offbase?

**Comment by jadiehm** [comment]
Totally get that! I do think it's important to shine light on the truly awful things that police are doing and saying. I'm happy to take all a look at any others that you find, but I expect that it might be hard to find a complaint without any sort of slur in it. I think ultimately I'm ok with including them, I'd just try to highlight around the slur if possible. Like in the one you currently have, highlighting the first and last sentence would let the reader know broadly what the complaint was about, but wouldn't immediately draw their eye to the most offensive text unless they actively chose to read more.
