### ISSUE TITLE
sam to send brief bio for website (1-2 sentences), including whether he'd like a link to his site, twitter profile, and email address

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/police_misconduct_pudding#21]

**Comment by sdl60660** [comment]
For the bio, I think just something like:

"Sam Learner is a developer and analyst now living in Pittsburgh. He's interested in visualizing public data to make it more accessible."

email: learnersd@gmail.com
website: www.samlearner.com
twitter: https://twitter.com/sam_learner
