### ISSUE TITLE
on mobile, the complaint on the tile chart is cut off

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/police_misconduct_pudding#22]
![image](https://user-images.githubusercontent.com/2880174/97315946-9e228200-183f-11eb-968a-ed3cdf5a0db6.png)

**Comment by sdl60660** [comment]
Seems to depend on the exact phone size, but switching the d3-tip width from calc(100vw - 50px) to calc(100vw - 20px) seems to fix it.
