### ISSUE TITLE
tooltips on tilechart run off screen—consider a clipped version , an interaction where you click and then are able to scroll through the tooltip, or moving the full complaint to a more fixed position

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/police_misconduct_pudding#6]

**Comment by sdl60660** [comment]
On desktop right?

**Comment by sdl60660** [comment]
Ah, I see, there's a couple near the top of the "guilty finding" block, right? I think we could just slightly increase the max-width of the complaint tooltip and fix this. All those are oriented to the left so there's plenty more horizontal space to work with. (As long as you're not seeing a more widespread issue than I am)

**Comment by sdl60660** [comment]
This should be fixed now. Increased the max-width on .d3-tip by 30px and added a breakpoint at max-width: 1250px to lower the font-size.
