### ISSUE TITLE
Squares overall: There needs to be some sort of note about how we're showing the raw, unedited text of the complaints and that there may be offensive languages.

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/police_misconduct_pudding#7]

**Comment by matthewfdaniels** [comment]
@sdl60660 can you add this in?

**Comment by sdl60660** [comment]
Added the following sentence to the bottom of tilechart 2: "Note that the summaries contain the raw, unedited text of complaints and may contain language that is offensive or graphic."
